Make title optional on Menu
element-hq/compound-web pull request #174
Opened 2024-05-28 17:56 UTC by dbkr

2024-05-28 18:21 UTC, t3chguy reviewed
I feel like if a title is not provided then a label must be, can the types reflect this?

2024-05-28 18:37 UTC, dbkr commented
Not sure what you mean... there is no prop for label, or were you suggesting adding one?

2024-05-29 14:45 UTC, t3chguy requested changes

2024-05-29 14:45 UTC, t3chguy commented on src/components/Menu/FloatingMenu.tsx
> +        aria-labelledby={title ? titleId : undefined}
```suggestion
        aria-labelledby={showTitle ? titleId : undefined}
```

2024-05-30 10:10 UTC, merged