Add in-progress view to EditInPlace component
element-hq/compound-web pull request #180
Opened 2024-06-12 16:28 UTC by dbkr

Adds the InlineSpinner component so we can use it. Also tweaks a
lot of the spacing & sizing of the caption icons in EditInPlace
to get them right.

Based on https://github.com/element-hq/compound-web/pull/179

2024-06-12 16:47 UTC, t3chguy requested changes

2024-06-12 16:47 UTC, t3chguy commented on playwright/visual.test.ts-snapshots/Form-Controls-EditInPlace-With-Error-1-chromium-linux.png
the v-align between the icon and the text seems to have gotten messed up

2024-06-12 16:47 UTC, t3chguy commented on playwright/visual.test.ts-snapshots/InlineSpinner-Default-1-chromium-linux.png
This screenshot seems brittle, given its animated

2024-06-13 11:04 UTC, dbkr commented on playwright/visual.test.ts-snapshots/InlineSpinner-Default-1-chromium-linux.png
Playwright disables animations by default on screenshots (https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-name) so this one will be canceled to its initial state.

2024-06-13 11:06 UTC, t3chguy approved these changes

2024-06-14 09:21 UTC, merged